version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    ports: 
     - "5050:5050"

  client:
    container_name: client
    build:
      context: ./client
      target: development
    command: npm run dev -- --host
    volumes:
      - ./client:/usr/app
      - ./usr/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - server